### PR TITLE
Feature/teamstab

### LINKED ISSUE #22: Team tab
Similar to this: https://ohbm.github.io/hackathon2023/team/

We can grab frames from canva.

### PR DESCRIPTION
**Pull request by mashcodes10**
Added teams tab!
The menu is not in the home. However, the route has been added to the app directory.
So, http://localhost:3000/#/teams will work.
Attached Preview:
image

### CODE REVIEW

**Comment by rgbayrak** [comment]
- [x] Remove the square hue around the images. 
- [x] In place of city,state > add team roles
- [ ] if more than 3 in a row would be better imo ( perhaps 4-5-4 asym?)

**Comment by rgbayrak** [comment]
is the typewriter effect in the same PR?

**Comment by mashcodes10** [comment]
> is the typewriter effect in the same PR?

No I have cloned the latest one with photos and the typewriter wasn't merged in that one

**Comment by shansitads** [comment]
Modifications made:
- Removed the dark background and rectangular hover around each person's card
- Made github and location information optional (github link be included by adding the "ghlink" information in the teamsData.js file)
- Added committee-specific allotments
- Updated team members
- Added placeholder images for all members without headshors
Screenshot 2024-12-04 at 7 24 33 PM
Screenshot 2024-12-04 at 7 26 44 PM

**Comment by shansitads** [comment]
@mashcodes10 Could you have a look into 2 things
- Why is there the dark background behind the images (it's a dark purple square in yours which I tried to make smaller by making it circular but we'd like to get rid of it entirely)
- Can the members be arranged in rows of 5 (or alternating rows of 5-4-5-4 in a staggered structure)

**Comment by shansitads** [comment]
current version updates
- team leads in a separate row
- faculty advisers in a separate row
- removed section headers
Screenshot 2024-12-04 at 9 24 28 PM

**Pull request merged**
