### PR TITLE
Edited sponsors section

### PR DESCRIPTION
**Pull request by rgbayrak**
- fixed style and sponsor logos
- added github fork/star

### CODE REVIEW

**Comment by rgbayrak** [comment]
Screenshot 2024-11-18 at 2 53 29 PM

**Comment by rgbayrak** [comment]
closes #12

**Comment by shansitads** [comment]
The new sponsors section is causing the horizontal scroll to be generated at the bottom – can it be made smaller @rgbayrak  ?
Screenshot 2024-11-18 at 4 37 41 PM

**Comment by shansitads** [comment]
Mobile screen display:
Screenshot 2024-11-18 at 11 10 32 PM

**Pull request merged**
