### PR TITLE
Added Typewriter

### LINKED ISSUE #10: Bring back the typewriter effect
Rotate these below on the landing page:
Researchers
Software developers
Clinicians 
Surgeons  
Students 
Faculty
Postdocs

### PR DESCRIPTION
**Pull request by mashcodes10**
Typewrite is now live. It looked better in my eyes when it is above the data with the same font as headings. One issue could be it might not be responsive.

### CODE REVIEW

**Comment by rgbayrak** [comment]
Can you share a screenshot of how it looks on your landing page?

**Comment by mashcodes10** [comment]
I think a video will be more appropriate in this case: https://drive.google.com/drive/folders/1HBBW4of1ujaEH09Mwgn5R_4Zb3nxIalf?usp=sharing

**Comment by shansitads** [comment]
@mashcodes10 
Could you 1) reduce the vertical padding and 2) reduce the font size to be the same as the date?

Current version for reference:
Screenshot 2024-11-18 at 11 39 56 PM

**Comment by mashcodes10** [comment]
Reduced vertical padding and font size to align with date
Latest commit: 
Screenshot 2024-11-21 at 1 28 40 PM

**Comment by rgbayrak** [comment]
Is there a way to remove that large space (it seems like it is pushing the date and apply button away) or is that intentional? @mashcodes10

**Comment by shansitads** [comment]
reduced spacing more
Screenshot 2024-12-05 at 12 07 24 AM

**Pull request merged**
